import type { CollaboratorActivity } from "../types";

// Datos de ejemplo (NO reales) para previsualizar la trazabilidad de un
// colaborador antes de que la base de datos tenga historial real. Cubre los
// tipos de acción (creación, asignación, cambios de estado, comentario),
// entregas, una devolución y un comentario de avance.
export const MOCK_ACTIVITY: CollaboratorActivity = {
  user_id: "demo",
  name: "Ana",
  last_name: "López",
  email: "ana.lopez@objdigital.com",
  position: "diseñador_grafico",
  assigned_tasks: 6,
  completed_tasks: 3,
  in_progress_tasks: 2,
  completion_pct: 50,
  project_count: 3,
  team_count: 2,
  tasks: [
    {
      id: "t1",
      title: "Diseñar portada de la Unidad 1",
      status: "completada",
      due_date: "2026-06-10",
      completed_at: "2026-06-09T16:00:00Z",
    },
    {
      id: "t2",
      title: "Infografía del Módulo 2",
      status: "en_revision",
      due_date: "2026-06-22",
      completed_at: null,
    },
    {
      id: "t3",
      title: "Banners del curso de Fundamentos",
      status: "en_progreso",
      due_date: "2026-06-25",
      completed_at: null,
    },
    {
      id: "t4",
      title: "Plantilla de diapositivas",
      status: "devuelta",
      due_date: "2026-06-15",
      completed_at: null,
    },
    {
      id: "t5",
      title: "Iconografía de la plataforma",
      status: "pendiente_por_iniciar",
      due_date: "2026-07-01",
      completed_at: null,
    },
    {
      id: "t6",
      title: "Maquetación del syllabus",
      status: "completada",
      due_date: "2026-06-05",
      completed_at: "2026-06-05T11:30:00Z",
    },
  ],
  // Historial en orden descendente por fecha (lo más reciente primero).
  history: [
    {
      id: "h1",
      task_id: "t3",
      task_title: "Banners del curso de Fundamentos",
      action: "comentario",
      old_status: null,
      new_status: null,
      change_reason: "Avanzo el 60%, faltan las versiones para móvil",
      created_at: "2026-06-18T14:20:00Z",
    },
    {
      id: "h2",
      task_id: "t1",
      task_title: "Diseñar portada de la Unidad 1",
      action: "cambio_estado",
      old_status: "en_revision",
      new_status: "completada",
      change_reason: "Entrega aprobada por el revisor",
      created_at: "2026-06-09T16:00:00Z",
    },
    {
      id: "h3",
      task_id: "t2",
      task_title: "Infografía del Módulo 2",
      action: "cambio_estado",
      old_status: "en_progreso",
      new_status: "en_revision",
      change_reason: "Enviada a revisión",
      created_at: "2026-06-08T10:15:00Z",
    },
    {
      id: "h4",
      task_id: "t4",
      task_title: "Plantilla de diapositivas",
      action: "cambio_estado",
      old_status: "en_revision",
      new_status: "devuelta",
      change_reason: "Devuelta: ajustar la paleta a la marca",
      created_at: "2026-06-07T17:45:00Z",
    },
    {
      id: "h5",
      task_id: "t3",
      task_title: "Banners del curso de Fundamentos",
      action: "cambio_estado",
      old_status: "pendiente_por_iniciar",
      new_status: "en_progreso",
      change_reason: null,
      created_at: "2026-06-05T09:00:00Z",
    },
    {
      id: "h6",
      task_id: "t3",
      task_title: "Banners del curso de Fundamentos",
      action: "reasignacion",
      old_status: null,
      new_status: null,
      change_reason: "Reasignada al equipo de diseño gráfico",
      created_at: "2026-06-04T12:00:00Z",
    },
    {
      id: "h7",
      task_id: "t6",
      task_title: "Maquetación del syllabus",
      action: "cambio_estado",
      old_status: "en_revision",
      new_status: "completada",
      change_reason: "Entrega aprobada",
      created_at: "2026-06-05T11:30:00Z",
    },
    {
      id: "h8",
      task_id: "t1",
      task_title: "Diseñar portada de la Unidad 1",
      action: "creacion",
      old_status: null,
      new_status: null,
      change_reason: "Tarea creada",
      created_at: "2026-06-01T08:00:00Z",
    },
  ],
};
