import type { ProjectTraceability, TraceabilityEvent } from "@/features/projects/types/api.types";

// Datos de ejemplo (NO reales) para previsualizar el diseño de la línea de
// tiempo antes de poblar la base de datos. Cubre todos los tipos de evento y
// varios retrasos, para validar colores y el resumen de un vistazo.
const MOCK_EVENTS: TraceabilityEvent[] = [
  {
    id: "m1",
    task_id: "t1",
    task_title: "Guion de la Unidad 1",
    actor_name: "Ana López",
    action: "comentario",
    old_status: null,
    new_status: null,
    change_reason: "Reporta retraso por dependencia pendiente",
    created_at: "2026-06-17T12:00:00Z",
    kind: "comentario",
    is_delay: false,
  },
  {
    id: "m2",
    task_id: "t1",
    task_title: "Guion de la Unidad 1",
    actor_name: "Ana López",
    action: "cambio_estado",
    old_status: "en_progreso",
    new_status: "en_progreso",
    change_reason: "Sigue en progreso tras la fecha límite",
    created_at: "2026-06-17T11:00:00Z",
    kind: "inicio",
    is_delay: true,
  },
  {
    id: "m3",
    task_id: "t2",
    task_title: "Aprobar plan con el cliente",
    actor_name: "Carlos Pérez",
    action: "cambio_estado",
    old_status: "devuelta",
    new_status: "en_revision",
    change_reason: "Reenvía con correcciones",
    created_at: "2026-06-15T09:00:00Z",
    kind: "entrega",
    is_delay: false,
  },
  {
    id: "m4",
    task_id: "t2",
    task_title: "Aprobar plan con el cliente",
    actor_name: "María Restrepo",
    action: "cambio_estado",
    old_status: "en_revision",
    new_status: "devuelta",
    change_reason: "Devuelta: faltan objetivos de aprendizaje",
    created_at: "2026-06-14T16:30:00Z",
    kind: "devolucion",
    is_delay: false,
  },
  {
    id: "m5",
    task_id: "t2",
    task_title: "Aprobar plan con el cliente",
    actor_name: "Carlos Pérez",
    action: "cambio_estado",
    old_status: "en_progreso",
    new_status: "en_revision",
    change_reason: "Primera entrega para revisión",
    created_at: "2026-06-13T10:00:00Z",
    kind: "entrega",
    is_delay: false,
  },
  {
    id: "m6",
    task_id: "t3",
    task_title: "Definir cronograma y alcance",
    actor_name: "María Restrepo",
    action: "cambio_estado",
    old_status: "en_revision",
    new_status: "completada",
    change_reason: "Entrega aprobada",
    created_at: "2026-06-10T15:00:00Z",
    kind: "aprobacion",
    is_delay: false,
  },
  {
    id: "m7",
    task_id: "t3",
    task_title: "Definir cronograma y alcance",
    actor_name: "Juan Gómez",
    action: "cambio_estado",
    old_status: "pendiente_por_iniciar",
    new_status: "en_progreso",
    change_reason: null,
    created_at: "2026-06-02T08:30:00Z",
    kind: "inicio",
    is_delay: false,
  },
  {
    id: "m8",
    task_id: "t3",
    task_title: "Definir cronograma y alcance",
    actor_name: "Líder de proyecto",
    action: "reasignacion",
    old_status: null,
    new_status: null,
    change_reason: "Asignación inicial del responsable",
    created_at: "2026-06-01T09:00:00Z",
    kind: "asignacion",
    is_delay: false,
  },
  {
    id: "m9",
    task_id: "t3",
    task_title: "Definir cronograma y alcance",
    actor_name: "Líder de proyecto",
    action: "creacion",
    old_status: null,
    new_status: null,
    change_reason: "Tarea creada",
    created_at: "2026-06-01T08:00:00Z",
    kind: "creacion",
    is_delay: false,
  },
];

const _DELIVERY_KINDS = new Set(["entrega", "aprobacion"]);

export const MOCK_TRACEABILITY: ProjectTraceability = {
  project_id: "demo",
  events: MOCK_EVENTS,
  summary: {
    total_events: MOCK_EVENTS.length,
    delays: MOCK_EVENTS.filter((e) => e.is_delay).length,
    deliveries: MOCK_EVENTS.filter((e) => _DELIVERY_KINDS.has(e.kind)).length,
    returns: MOCK_EVENTS.filter((e) => e.kind === "devolucion").length,
  },
};
