repos:
  # Backend
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'cd backend && poetry run pytest ./tests/unit'
        language: system
        pass_filenames: false
        files: ^backend/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        files: ^backend/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: [ --fix ]
        files: ^backend/

      - id: ruff-format
        files: ^backend/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry -C backend run pytest tests/unit
        language: system
        pass_filenames: false
        files: ^backend/


  # Frontend
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0
    hooks:
      - id: eslint
        files: ^frontend/
