"""Create all schemas

Revision ID: c6850d73cd90
Revises: 268b47aba4fb
Create Date: 2026-05-28 16:21:21.533294

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6850d73cd90"
down_revision: Union[str, Sequence[str], None] = "268b47aba4fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("client_name", sa.String(length=200), nullable=True),
        sa.Column("current_status_id", sa.UUID(), nullable=True),
        sa.Column("coordinator_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.String(length=10), nullable=True),
        sa.Column("end_date", sa.String(length=10), nullable=True),
        sa.Column("progress_pct", sa.Float(), nullable=False),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("duplicated_from_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["coordinator_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["current_status_id"],
            ["project_statuses.id"],
            name="fk_projects_current_status_id",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["duplicated_from_id"], ["projects.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projects_coordinator_id"), "projects", ["coordinator_id"], unique=False
    )
    op.create_index(
        op.f("ix_projects_current_status_id"),
        "projects",
        ["current_status_id"],
        unique=False,
    )
    op.create_table(
        "alert_rules",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "TASK_OVERDUE",
                "TASK_DUE_SOON",
                "TASK_ASSIGNED",
                "TASK_STATUS_CHANGED",
                "PROJECT_STATUS_CHANGED",
                "REPORT_GENERATED",
                "SCHEDULE_REPROGRAMMED",
                "WEEKLY_SUMMARY",
                "CUSTOM",
                name="alert_notification_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "frequency",
            sa.Enum("IMMEDIATE", "DAILY", "WEEKLY", name="alert_frequency"),
            nullable=False,
        ),
        sa.Column("days_before_due", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_rules_project_id"), "alert_rules", ["project_id"], unique=False
    )
    op.create_table(
        "client_accesses",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.String(length=30), nullable=True),
        sa.Column("last_accessed_at", sa.String(length=30), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_accesses_project_id"),
        "client_accesses",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_client_accesses_token"), "client_accesses", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_client_accesses_user_id"), "client_accesses", ["user_id"], unique=False
    )
    op.create_table(
        "modules",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("progress_pct", sa.Float(), nullable=False),
        sa.Column("duplicated_from_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["duplicated_from_id"], ["modules.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_modules_project_id"), "modules", ["project_id"], unique=False
    )
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("COORDINATOR", "MEMBER", "OBSERVER", name="project_member_role"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "user_id", name="uq_project_member"),
    )
    op.create_index(
        op.f("ix_project_members_project_id"),
        "project_members",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_members_user_id"), "project_members", ["user_id"], unique=False
    )
    op.create_table(
        "project_statuses",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_base", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.Column(
            "base_type",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "IN_REVIEW",
                "COMPLETED",
                "ON_HOLD",
                "CANCELLED",
                name="project_status_type",
            ),
            nullable=True,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_project_status_name"),
    )
    op.create_index(
        op.f("ix_project_statuses_project_id"),
        "project_statuses",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "report_schedules",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum("WEEKLY", "BIWEEKLY", "MONTHLY", name="report_frequency"),
            nullable=False,
        ),
        sa.Column(
            "day_of_week",
            sa.Enum(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                name="report_day_of_week",
            ),
            nullable=False,
        ),
        sa.Column(
            "report_type",
            sa.Enum(
                "EXECUTIVE_SUMMARY",
                "STATUS_REPORT",
                "CLIENT_SUMMARY",
                "RISK_REPORT",
                name="scheduled_report_type",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_generated_at", sa.String(length=30), nullable=True),
        sa.Column("send_by_email", sa.Boolean(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_report_schedules_project_id"),
        "report_schedules",
        ["project_id"],
        unique=True,
    )
    op.create_table(
        "reports",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "report_type",
            sa.Enum(
                "EXECUTIVE_SUMMARY",
                "STATUS_REPORT",
                "CLIENT_SUMMARY",
                "RISK_REPORT",
                name="report_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.Enum("MANUAL", "SCHEDULED", name="report_trigger"),
            nullable=False,
        ),
        sa.Column("generated_by_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=True),
        sa.Column("prompt_used", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("model_used", sa.String(length=50), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["generated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reports_project_id"), "reports", ["project_id"], unique=False
    )
    op.create_table(
        "risks",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "level",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="risk_level"),
            nullable=False,
        ),
        sa.Column("mitigation", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_risks_project_id"), "risks", ["project_id"], unique=False)
    op.create_table(
        "schedules",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("baseline_start", sa.String(length=10), nullable=True),
        sa.Column("baseline_end", sa.String(length=10), nullable=True),
        sa.Column("current_start", sa.String(length=10), nullable=True),
        sa.Column("current_end", sa.String(length=10), nullable=True),
        sa.Column("total_delay_days", sa.Integer(), nullable=False),
        sa.Column("total_tasks", sa.Integer(), nullable=False),
        sa.Column("completed_tasks", sa.Integer(), nullable=False),
        sa.Column("overdue_tasks", sa.Integer(), nullable=False),
        sa.Column("is_baseline_locked", sa.Boolean(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schedules_project_id"), "schedules", ["project_id"], unique=True
    )
    op.create_table(
        "reprogrammings",
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("requested_by_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("previous_dates_json", sa.Text(), nullable=True),
        sa.Column("new_dates_json", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["requested_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reprogrammings_schedule_id"),
        "reprogrammings",
        ["schedule_id"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=True),
        sa.Column("parent_task_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "task_type",
            sa.Enum("TASK", "SUBTASK", "ACTIVITY", "MILESTONE", name="task_type"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="task_priority"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "BLOCKED",
                "IN_REVIEW",
                "DONE",
                "CANCELLED",
                name="task_status",
            ),
            nullable=False,
        ),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("start_date", sa.String(length=10), nullable=True),
        sa.Column("due_date", sa.String(length=10), nullable=True),
        sa.Column("progress_pct", sa.Float(), nullable=False),
        sa.Column("delay_days", sa.Integer(), nullable=False),
        sa.Column("is_overdue", sa.Boolean(), nullable=False),
        sa.Column("duplicated_from_id", sa.UUID(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("estimated_hours", sa.Float(), nullable=True),
        sa.Column("actual_hours", sa.Float(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["duplicated_from_id"], ["tasks.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["module_id"], ["modules.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tasks_assignee_id"), "tasks", ["assignee_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_module_id"), "tasks", ["module_id"], unique=False)
    op.create_index(
        op.f("ix_tasks_parent_task_id"), "tasks", ["parent_task_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "gantt_entries",
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("baseline_start", sa.String(length=10), nullable=True),
        sa.Column("baseline_end", sa.String(length=10), nullable=True),
        sa.Column("planned_start", sa.String(length=10), nullable=True),
        sa.Column("planned_end", sa.String(length=10), nullable=True),
        sa.Column("actual_start", sa.String(length=10), nullable=True),
        sa.Column("actual_end", sa.String(length=10), nullable=True),
        sa.Column("is_milestone", sa.Boolean(), nullable=False),
        sa.Column("is_critical_path", sa.Boolean(), nullable=False),
        sa.Column("delay_days", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gantt_entries_schedule_id"),
        "gantt_entries",
        ["schedule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gantt_entries_task_id"), "gantt_entries", ["task_id"], unique=True
    )
    op.create_table(
        "notifications",
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("related_task_id", sa.UUID(), nullable=True),
        sa.Column(
            "notification_type",
            sa.Enum(
                "TASK_OVERDUE",
                "TASK_DUE_SOON",
                "TASK_ASSIGNED",
                "TASK_STATUS_CHANGED",
                "PROJECT_STATUS_CHANGED",
                "REPORT_GENERATED",
                "SCHEDULE_REPROGRAMMED",
                "WEEKLY_SUMMARY",
                "CUSTOM",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("EMAIL", "IN_APP", name="notification_channel"),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_sent", sa.Boolean(), nullable=False),
        sa.Column("sent_at", sa.String(length=30), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["related_task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_project_id"),
        "notifications",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_recipient_id"),
        "notifications",
        ["recipient_id"],
        unique=False,
    )
    op.create_table(
        "task_comments",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_edited", sa.Boolean(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_comments_task_id"), "task_comments", ["task_id"], unique=False
    )
    op.create_table(
        "task_dependencies",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_id", sa.UUID(), nullable=False),
        sa.Column(
            "dependency_type",
            sa.Enum(
                "FINISH_TO_START",
                "START_TO_START",
                "FINISH_TO_FINISH",
                "START_TO_FINISH",
                name="dependency_type",
            ),
            nullable=False,
        ),
        sa.Column("lag_days", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["depends_on_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "depends_on_id", name="uq_task_dependency"),
    )
    op.create_index(
        op.f("ix_task_dependencies_depends_on_id"),
        "task_dependencies",
        ["depends_on_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_dependencies_task_id"),
        "task_dependencies",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "task_status_history",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("changed_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "BLOCKED",
                "IN_REVIEW",
                "DONE",
                "CANCELLED",
                name="task_status_from",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "BLOCKED",
                "IN_REVIEW",
                "DONE",
                "CANCELLED",
                name="task_status_to",
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["changed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_status_history_task_id"),
        "task_status_history",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "delivery_logs",
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("smtp_message_id", sa.String(length=200), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"], ["notifications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_delivery_logs_notification_id"),
        "delivery_logs",
        ["notification_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delivery_logs_notification_id"), table_name="delivery_logs")
    op.drop_table("delivery_logs")
    op.drop_index(
        op.f("ix_task_status_history_task_id"), table_name="task_status_history"
    )
    op.drop_table("task_status_history")
    op.drop_index(op.f("ix_task_dependencies_task_id"), table_name="task_dependencies")
    op.drop_index(
        op.f("ix_task_dependencies_depends_on_id"), table_name="task_dependencies"
    )
    op.drop_table("task_dependencies")
    op.drop_index(op.f("ix_task_comments_task_id"), table_name="task_comments")
    op.drop_table("task_comments")
    op.drop_index(op.f("ix_notifications_recipient_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_project_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_gantt_entries_task_id"), table_name="gantt_entries")
    op.drop_index(op.f("ix_gantt_entries_schedule_id"), table_name="gantt_entries")
    op.drop_table("gantt_entries")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_parent_task_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_module_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assignee_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_reprogrammings_schedule_id"), table_name="reprogrammings")
    op.drop_table("reprogrammings")
    op.drop_index(op.f("ix_schedules_project_id"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_index(op.f("ix_risks_project_id"), table_name="risks")
    op.drop_table("risks")
    op.drop_index(op.f("ix_reports_project_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_report_schedules_project_id"), table_name="report_schedules")
    op.drop_table("report_schedules")
    op.drop_index(op.f("ix_project_statuses_project_id"), table_name="project_statuses")
    op.drop_table("project_statuses")
    op.drop_index(op.f("ix_project_members_user_id"), table_name="project_members")
    op.drop_index(op.f("ix_project_members_project_id"), table_name="project_members")
    op.drop_table("project_members")
    op.drop_index(op.f("ix_modules_project_id"), table_name="modules")
    op.drop_table("modules")
    op.drop_index(op.f("ix_client_accesses_user_id"), table_name="client_accesses")
    op.drop_index(op.f("ix_client_accesses_token"), table_name="client_accesses")
    op.drop_index(op.f("ix_client_accesses_project_id"), table_name="client_accesses")
    op.drop_table("client_accesses")
    op.drop_index(op.f("ix_alert_rules_project_id"), table_name="alert_rules")
    op.drop_table("alert_rules")
    op.drop_index(op.f("ix_projects_current_status_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_coordinator_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
