"""Remove complex relationshit from user model

Revision ID: d479caaa7c77
Revises: 4e5fb6fc637f
Create Date: 2026-05-25 16:55:36.060074

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d479caaa7c77"
down_revision: Union[str, Sequence[str], None] = "4e5fb6fc637f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
